### ISSUE TITLE
VS2017 Support

### ISSUE THREAD

**Issue by mcintyre321** [realvizu/NsDepCop#14]
Hi, is VS2017 support planned? Thanks for the awesome tool.

**Comment by realvizu** [comment]
Absolutely, but I don't know yet when.

**Comment by realvizu** [comment]
Fortunately the new [NuGet package](https://www.nuget.org/packages/NsDepCop/1.6.0) distribution does not depend on a concrete Visual Studio version, so you can use it in VS2017 projects too. I've just tried, works.

The things that do not work yet in VS2017 are the instant code analysis (the VSIX package) and the config XML schema support (in the MSI installer).
