### ISSUE TITLE
Wildcards don't work in front of namespace

### ISSUE THREAD

**Issue by MichaelTR2** [realvizu/NsDepCop#24]
I want to whitelist something like this:
`<Allowed From="*" To="*.Contract" />`
Which means that all namespaces should be allowed to reference namespaces ending on .Contract.

But this doesn't seem to work.

**Comment by realvizu** [comment]
That's right, the tool supports wildcard usage only at the end of a namespace.

Background:
The tool's approach to rule matching is structural, not textual. That is, it examines logical containment in the namespace hierarchy, not textual match of namespace strings. Changing this behavior would be quite substantial.
