### ISSUE TITLE
Support leading wildcard.

### ISSUE THREAD

**Issue by p-gag** [realvizu/NsDepCop#28]
Hello, Thank you for this lib, it help us a lot. 

I was wondering if it would be possible to support leading wildcard to achieve something like:  
\<Allowed From="\*.UI" To="MyUiLib.\*"\>

**Comment by realvizu** [comment]
This is a major work item and won't make it to v1.8. Moving to v1.9.

**Comment by mgoutrie** [comment]
Hello,

as we name our packages and namespaces like `Area.Layer.Topic.Api`, `Area.Layer.Topic.Impl` and `Area.Layer.Topic.SecondaryApi` I'd be interested in a namespace definition with some wildcard logic (which includes the leading '*').
e.g. 
- `Area.Infra.*.Impl` -> `Area.?.?.Api`
- `Area.Infra.*.Impl` -> `Area.Core.*.Impl`

I could imagine a syntax like shown  below in a unit test (`?`means exactly one namespace component  and `*` means zero or more namespace components.) This would be compatible with the existing syntax.

```
public class ExtendedSystaxDistanceTests
    {
        [Theory]
        [InlineData("A.C.D", "A.C.D", 0)] // perfect match
        [InlineData("A.C.D", "A.?.D", 1)]
        [InlineData("A.C.D", "A.C.?", 1)]
        [InlineData("A.C.D", "?.C.D", 1)]
        [InlineData("A.C.D", "A.?.?", 2)]
        [InlineData("A.C.D", "?.?.D", 2)]
        [InlineData("A.C.D", "?.?.?", 3)]
        [InlineData("A.C.D", "A.*", 3)]
        [InlineData("A.C.D", "*.D", 3)]
        [InlineData("A.C.D", "*.?.D", 3)]
        [InlineData("A.B.C.D", "*.?.D", 4)]
        [InlineData("A.C.D", "*", 4)]
        [InlineData("A.C.D", "B.?.D", int.MaxValue)] // no match
        [InlineData("A.C.D", "*.E", int.MaxValue)] // no match
        public void ExpectedDistance(string actual, string pattern, int distance)
        {
            NamespaceSpecification patternNs = pattern.Any(s => s == '*' || s == '?') ? new WildcardNamespace(pattern) : new Namespace(pattern);
            var ns = new Namespace(actual);

            patternNs.GetMatchRelevance(ns).Should().Be(int.MaxValue - distance);
        }
    }
```

An alternative syntax could be `**` instead of `*`and `*` instead of `?` which is not compatible and had to be activated with an attribute in the configuration file.

I'm currently working on a solution like described above (it's in the test phase). 
Would you include it in to the code base or should it keep a fork?

**Comment by realvizu** [comment]
I'd love to include it, preferably with the non-breaking (* and ?) syntax.
Looking forward to the PR.
Again, thanks a lot for your work!

**Comment by mgoutrie** [comment]
Just for your information: I'm still active on this topic, but have to complete some higher priorized tasks first :( I expect to continue at the end of next week.

**Comment by plainionist** [comment]
is there still any activity on that topic?
i would be interested in similar enhancement and would like to know about the work which already has been done before reinventing the wheel.

**Comment by realvizu** [comment]
Pinging @mgoutrie . Can we still expect that PR or something came up?

**Comment by plainionist** [comment]
while waiting i created a first prototype ;-)

https://github.com/plainionist/NsDepCop/commit/22f2643600efd73055cbd7ce1b22ba22cef84ec7

what do u think about it?

**Comment by realvizu** [comment]
Thanks for working on this!

My thoughts:
* Please add tests to TypeDependencyValidatorTests so we can see that the pattern matching works as expected.
* Please clean up comments in NamespacePattern. Some still talk about namespace trees, and the mentioning of 'any namespace' is not relevant here.
* I'm a bit concerned about the performance of using a regex but I like that in NamespaceSpecificationParser you instantiate a NamespacePattern only if needed and fall back to NamespaceTree/Namespace when possible. So I would guess that there's no performance hit for existing useres with legacy configs (that contain only NamespaceTree/Namespace rules).
* In NamespacePatternTests.GetMatchRelevance_Succeeds I would expect that InlineData("A.*.B") should NOT match "A.F1.B.C" and should give MatchRelevance = 0. What am I missing here?
* Could you add test cases for leading wildcards too? (eg. "*.B")
* It would be nice to see some performance benchmarks using [BenchmarkDotNet](https://benchmarkdotnet.org/Overview.htm) so we can compare the performance of a NamespacePattern compared to a NamespaceTree so we can advise users about the expected performance hit (if there's any) of using the regex patterns. But it's a nice-to-have thing so no worries if you don't have time for that.

**Comment by mgoutrie** [comment]
Sorry for the delay. But I'm always carrying a big bag of open tasks in my work...

The current status is:
We use the code in https://github.com/mgoutrie/NsDepCop/tree/test/wildcards in one bigger project in production and encountered no functional or performance problems. 

@realvizu  The points you mentioned in your last post are exactly the ones I had in mind before creating a pull request.
The `InlineData("A.*.B") should NOT match "A.F1.B.C"` case seems strange to me too.

I'm back from holidays today and promise to complete this this week (if no massive problems occur).

Hope you are patient with me...

**Comment by realvizu** [comment]
Well, this is voluntary work so no hard feelings about delays. :)
All contributions are much appreciated!

**Comment by plainionist** [comment]
@realvizu thx for your feedback! i would look into your points but now that @mgoutrie continues i will pause my activities - i think we don't need two implementations for this ;-)

@mgoutrie  pls keep us updated - if you don't find the time to finish your work i may continue here next week

thx!

**Comment by mgoutrie** [comment]
@plainionist FYI: I created the pull request.

**Comment by realvizu** [comment]
Merged and released to: https://www.nuget.org/packages/NsDepCop
@mgoutrie thanks for the contribution!
@plainionist thanks for the nudge! :)

**Comment by plainionist** [comment]
hey cool - thx a lot! i ll try it out soon!

**Comment by plainionist** [comment]
i tested verison 2.2

these rules work perfectly fine

  <Allowed From="NC.?.IO.*" To="NC.Core.*" />
  <Allowed From="NC.?.IO.*" To="LiteDB" />

this one does not seem to work:

  <Allowed From="NC.?.IO.*" To="NC.Orchestrator.*" />

dependencies from "NC.Orchestrator.IO" to "NC.Orchestrator.Adapters" are reported as error 

shouldn't the rule cover such dependencies?

**Comment by mgoutrie** [comment]
I tested this with a unit test (in class TypeDependencyValidatorTests):
```cs
        [Fact]
        public void TestPlainionist()
        {
            var ruleConfig = new DependencyRulesBuilder()
                .AddAllowed("NC.?.IO.*", "NC.Orchestrator.*");

            var dependencyValidator = CreateTypeDependencyValidator(ruleConfig);
            dependencyValidator.IsAllowedDependency("NC.Orchestrator.IO", "C", "NC.Orchestrator.Adapters", "C1").Should().BeTrue();
        }
```

... and the test succeeded.
Is there any Disallow-rule matching these namespaces?

**Comment by plainionist** [comment]
i just reopened visual studio today morning and it worked as expected - strange.
thx for checking it again!
