### ISSUE TITLE
How to disallow NS reference except for ...

### ISSUE THREAD

**Issue by zhangxin511** [realvizu/NsDepCop#54]
To whom it may concern, need your suggestions: 
Say in my system, I have one `Admin` NS very dangerous. I only want it to be accessed internally, and forbid external reference, with one except, say `BusinessForAdmin` NS on some other module. I made the following rules:
```
    <Allowed From="*" To="*" />     <!--No restrictions just like not used this package before-->
    <Disallowed From="*" To="Admin.*" />     <!--Disallow any access to Admin.* since it is  risky-->
    <Allowed From="BusinessForAdmin.*" To=Admin.*" />    <!--Except for BusinessForAdmin, must have visibility toAdmin.* -->
```

But according to the docs: 
1. The sequence is not the matter, 
2. Disallow is stronger than Allow

so the above block will not work since the `<Disallowed From="*" To="Admin.*" />` win and no one is able to access the Admin.

But How to do I get Don't allow beside some NS?

**Comment by realvizu** [comment]
That's right, make exceptions from Disallowed rules are not supported.
But if you use only Allowed rules you might achieve what you want, because everything which is not explicitly allowed are implicitly disallowed.

```
<Allowed From="BusinessForAdmin.*" To=Admin.*" /> 
<!-- Only BusinessForAdmin can access Admin because every other thing is implicitly disallowed -->
```

And then you have to add Allowed rules for all the other namespaces.

```
<Allowed From="MyOtherRootNamespace.*" To="*" />
<Allowed From="*" To="MyOtherRootNamespace.*" />
```
etc.

Hope this helps.

**Comment by zhangxin511** [comment]
Thank you @realvizu Our codebase is relatively huge, don't think explicitly listing is manageable for us...
