### ISSUE TITLE
Add Allowed Types/Members to build warning

### ISSUE THREAD

**Issue by kirides** [realvizu/NsDepCop#67]
Currently if we only allow users a subset of Types in a namespace, the user won't know which types are allowed unless they read through configs and documentation.

```xml
<Allowed From="*" To="MassTransit">
	<VisibleMembers>
		<Type Name="IPublishEndpoint" />
		<Type Name="ISendEndpointProvider" />
		<Type Name="ISendEndpoint" />
	</VisibleMembers>
</Allowed>
```

i propose that the emitted error in such cases
```
Error NSDEPCOP01 : Illegal namespace reference: Service.Api->MassTransit (Type: SomeController->IBus)
```
becomes more like this:
```
Error NSDEPCOP01 : Illegal namespace reference: Service.Api->MassTransit (Type: SomeController->IBus) Allowed Types are: IPublishEndpoint, ISendEndpoint, ...
```

This would improve consuming such warnings/errors much easier

**Comment by realvizu** [comment]
Thanks for the proposal, this would be a helpful enhancement indeed.

If anyone wants to contribute, I'm happy to help you figure out how to implement and unit test it.

**Comment by SteveDunn** [comment]
I'd be happy to take a look at this one! I was just replying to someone and mentioned nsdepcop, and spotted this issue. I'd be happy to contribute to such a great utility!

**Comment by realvizu** [comment]
Great! Thanks for volunteering! 

Here are some thoughts that may help you get started.
* The error message that should be extended with allowed type info is defined here: DiagnosticDefinitions.IllegalDependency.
* This diagnostic is created in NsDepCopAnalyzer.AnalyzeSyntaxNodeAndReportDiagnostics. 
* The error message parameters are populated from an IllegalDependencyMessage. This type should be extended with an AllowedTypeNames collection.
* The IllegalDependencyMessage objects are created in DependencyAnalyzer.PerformAnalysis. It loops through the illegal type dependencies returned by GetIllegalTypeDependencies.
* GetIllegalTypeDependencies uses the _typeDependencyValidator member to decide whether a dependency is allowed or not, which is a descendant of TypeDependencyValidator.
* TypeDependencyValidator has all the info about the dependency rules. The allowed type names that we need are in the _allowRules and _visibleTypesPerNamespaces dictionaries.
* Note that there are 2 kinds of dependency rules that can contain allowed type names: the "normal" Allowed rules with VisibleMembers tag, and the "global" VisibleMembers tag, as described in Help.md / Namespace surface chapter.
* We have to modify the IsAllowedDependency method to return not only a bool but optionally the allowed type names too.
* But we should return the allowed type names only if the rule that produced the negative result actually has AllowedTypeNames, that is, if GetVisibleMembers returned a non-empty collection.

Regarding unit testing:
* It's the TypeDependencyValidatorTests class that contains the test cases for IsAllowedDependency.
* Consider the following methods that test the effect of the 2 kinds of VisibleMembers (when the VisibleMembers is inside an Allowed rule, or when it's a global VisibleMembers definition):
  * AllowRuleWithVisibleMembers_AffectsOnlyAllowRuleSource
  * AllowRule_GlobalVisibleMembers_AffectsAllRuleSources
* So either these methods should check whether the AllowedTypeNames info is returned correctly, or some new test methods should be created for this purpose.

* Also, there are end-to-end tests in the NsDepCop.SourceTest project. Specifically these test cases deal with VisibleMembers:
  * AnalyzerFeature_VisibleMembersOfAllowedRule
  * AnalyzerFeature_VisibleMembersOfNamespace
* These end-to-end tests use the SourceTestSpecification class to build up a test case, execute it, and perform the necessary asserts.
* The AssertIllegalDependencies method currently checks only whether the reported TypeDependency object's SourceSegment looks as expected. It should also check whether the expected AllowedTypeNames were also returned (if specified).
* Probably the ExpectInvalidSegment builder method should accept an optional extra parameter (AllowedTypeNames), so it can be checked in AssertIllegalDependencies.
* Which means that SourceTestSpecification.GetIllegalDependencies should also be refactored to either return the whole IllegalDependencyMessage, or both the TypeDependency and the AllowedTypeNames.

Hope I didn't overlook any serious roadblocks. 
Anyway, if you run into problems, then don't hesitate to reach out!

**Comment by realvizu** [comment]
Here's a quick overview of the types involved:
![image](https://github.com/realvizu/NsDepCop/assets/7570679/62448a44-0f5d-4c16-875f-a1b99f3ce7d7)

**Comment by SteveDunn** [comment]
Many thank for the detailed information! I'll hopefully have some time this week. Thanks again!

**Comment by realvizu** [comment]
The new version is live on NuGet: https://www.nuget.org/packages/NsDepCop/2.3.0
Thanks for the proposal and the implementation!
