### ISSUE TITLE
VS 2022- Dont see NsDepCop work in C# ClassLibrary (.Net Framework) project

### ISSUE THREAD

**Issue by edwin-alvarez** [realvizu/NsDepCop#70]
is NsDepCop supported on 
Target Framework = .Net Framework 4.8
Output Type = Class Library
Platform = any CPU (x64)

child project
config.NsDepCop
```
<NsDepCopConfig IsEnabled="true" ChildCanDependOnParentImplicitly="true" InheritanceDepth="1">
</NsDepCopConfig> 
```

root
config.NsDepCop
```
<NsDepCopConfig IsEnabled="true" ChildCanDependOnParentImplicitly="true" InheritanceDepth="">
	<Allowed From="*" To="System.*" />
	<Disallowed From="xxx" To="yyy"/>
</NsDepCopConfig>
```

**Comment by realvizu** [comment]
Yes, it's supported.
Try to remove the InheritanceDepth attribute from the root level file. Maybe the parser fails on the empty attribute value.

**Comment by edwin-alvarez** [comment]
Tested in new project and works great
